### ISSUE TITLE
Add scale in/out Dialog animatio

### ISSUE THREAD

**Issue by morewings** [morewings/koval-ui#444]
```css

.scale-in-ver-center {
	-webkit-animation: scale-in-ver-center 0.5s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
	        animation: scale-in-ver-center 0.5s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
}

``` 
https://animista.net/play/entrances/scale-in/scale-in-ver-center
